pushfirst!(LOAD_PATH, joinpath(@__DIR__, "..")) # add MLIR to environment stack

using MLIR
using Documenter

DocMeta.setdocmeta!(MLIR, :DocTestSetup, :(using MLIR); recursive=true)

# Generate examples

using Literate

const EXAMPLES_DIR = joinpath(@__DIR__, "..", "examples")
const OUTPUT_DIR = joinpath(@__DIR__, "src/generated")

examples = Pair{String,String}[
]

for (_, name) in examples
    example_filepath = joinpath(EXAMPLES_DIR, string(name, ".jl"))
    Literate.markdown(example_filepath, OUTPUT_DIR, documenter = true)
end

examples = [title => joinpath("generated", string(name, ".md")) for (title, name) in examples]

makedocs(;
    modules=[MLIR],
    authors="Valentin Churavy <vchuravy@mit.edu>, and others",
    repo="https://github.com/JuliaLabs/MLIR.jl/blob/{commit}{path}#{line}",
    sitename="MLIR.jl",
    format=Documenter.HTML(;
        prettyurls=get(ENV, "CI", "false") == "true",
        canonical="https://julia.mit.edu/MLIR.jl/",
        assets = [
            asset("https://plausible.io/js/plausible.js",
                    class=:js,
                    attributes=Dict(Symbol("data-domain") => "julia.mit.edu", :defer => "")
                )
	    ],
    ),
    pages = [
        "Home" => "index.md",
        "Examples" => examples,
        "IR" => [
            "AffineExpr" => "IR/affineexpr.md",
            "AffineMap" => "IR/affinemap.md",
            "Attribute" => "IR/attribute.md",
            "Block" => "IR/block.md",
            "Context" => "IR/context.md",
            "Dialect" => "IR/dialect.md",
            "Identifier" => "IR/identifier.md",
            "IntegerSet" => "IR/integerset.md",
            "Iterators" => "IR/iterators.md",
            "Location" => "IR/location.md",
            "LogicalResult" => "IR/logicalresult.md",
            "Module" => "IR/module.md",
            "Operation" => "IR/operation.md",
            # TODO `OpOperand` for LLVM >=16
            "Pass Infrastucture" => "IR/pass.md",
            "Region" => "IR/region.md",
            "SymbolTable" => "IR/symboltable.md",
            "Type" => "IR/type.md",
            "TypeID" => "IR/typeid.md",
            "Value" => "IR/value.md",
        ],
        "Dialects" => [
            "15" => [
                "`affine`" => "dialects/affine.md",
                "`amdgpu`" => "dialects/amdgpu.md",
                "`amx`" => "dialects/amx.md",
                "`arith`" => "dialects/arith.md",
                "`arm_neon`" => "dialects/arm_neon.md",
                "`arm_sve`" => "dialects/arm_sve.md",
                "`async`" => "dialects/async.md",
                "`bufferization`" => "dialects/bufferization.md",
                "`builtin`" => "dialects/builtin.md",
                "`complex`" => "dialects/complex.md",
                "`cf`" => "dialects/controlflow.md",
                "`emitc`" => "dialects/emitc.md",
                "`func`" => "dialects/func.md",
                "`gpu`" => "dialects/gpu.md",
                "`linalg`" => "dialects/linalg.md",
                "`llvm`" => "dialects/llvm.md",
                "`math`" => "dialects/math.md",
                "`memref`" => "dialects/memref.md",
                "`ml_program`" => "dialects/ml_program.md",
                "`nvgpu`" => "dialects/nvgpu.md",
                "`openacc`" => "dialects/openacc.md",
                "`openmp`" => "dialects/openmp.md",
                "`pdl`" => "dialects/pdl.md",
                "`pdl_interp`" => "dialects/pdl_interp.md",
                "`quant`" => "dialects/quant.md",
                "`scf`" => "dialects/scf.md",
                "`shape`" => "dialects/shape.md",
                "`sparse_tensor`" => "dialects/sparse_tensor.md",
                "`spv`" => "dialects/spirv.md",
                "`tensor`" => "dialects/tensor.md",
                "`tosa`" => "dialects/tosa.md",
                "`transforms`" => "dialects/transform.md",
                "`vector`" => "dialects/vector.md",
                "`x86vector`" => "dialects/x86vector.md",
            ],
        ],
        "API" => "api.md",
    ],
    doctest = true,
    strict = false, # due to autogenerated bindings
)

deploydocs(;
    repo="github.com/JuliaLabs/MLIR.jl",
    devbranch = "main",
    push_preview = true,
)